### ISSUE TITLE
Implement the cache

### ISSUE THREAD

**Issue by Haroenv** [algolia/gatsby-plugin-algolia#1]
Right now every build would add as many objects as there are results, we should cache them using the Gatsby cache

**Comment by Haroenv** [comment]
Will probably be able to be implemented with [atomic-algolia](https://yarnpkg.com/en/package/atomic-algolia).

**Comment by avigoldman** [comment]
Should this use atomic-algolia or follow the [atomic reindexing pattern](https://www.algolia.com/doc/tutorials/indexing/synchronization/atomic-reindexing/) of pushing into a temporary index and moving to the target index?

**Comment by Haroenv** [comment]
@avigoldman, either is good. I think I’d want to push the hashes of the objects in a separate index and compare though, but I haven’t found the time for this.

**Comment by avigoldman** [comment]
I'll open a PR doing an atomic reindex to keep it relatively straightforward to start.

**Comment by Haroenv** [comment]
Cool, very appreciated
