### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by bzmillerboy** [algolia/gatsby-plugin-algolia#106]
I just updated to v16 and I'm getting the following error during my build step.

<img width="606" alt="Screen Shot 2020-11-07 at 8 58 29 PM" src="https://user-images.githubusercontent.com/1130899/98455268-63242680-213c-11eb-976e-e55e41f7d50a.png">

```
  TypeError: Object.fromEntries is not a function
  
  - gatsby-node.js:405 getObjectsMapByQuery
    [web]/[gatsby-plugin-algolia]/gatsby-node.js:405:17
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

Gatsby v2.24.91
algoliasearch v4.6.0

**Comment by Haroenv** [comment]
you should use node 12+ or add a polyfill for it
