### ISSUE TITLE
Feature: Dry-run option for indexing (--dry-run)

### ISSUE THREAD

**Issue by bdenham** [algolia/gatsby-plugin-algolia#132]
It would be nice to have a boolean `dry-run` option that indexes, provides record count info, but doesn't push to Algoiia. Something comparable to what the jekyll-algolia plugin provides. I'd rather not burn through the monthly allotment of operations while developing the index. 

![image](https://user-images.githubusercontent.com/1828494/116768997-44be2a00-a9ff-11eb-8f0f-850afdfe2eb3.png)

**Comment by Haroenv** [comment]
That's a good idea, it could be part of the existing `skipIndexing` flag. are you interested in contributing?

**Comment by bdenham** [comment]
Absolutely! I'll do some investigation and open a PR. Thanks!

**Comment by naydav** [comment]
@Haroenv 
Looks like the feature was added in the scope of https://github.com/algolia/gatsby-plugin-algolia/pull/134
We can close this ticket
