### ISSUE TITLE
Could not parse the incoming response as JSON

### ISSUE THREAD

**Issue by nazanin-bayati** [algolia/gatsby-plugin-algolia#133]
Hi, 
I have done everything written in read me but still I face this error:
"  AlgoliaSearchUnparsableJSONError: Could not parse the incoming response as JSON, see err.more for details"

**Comment by Haroenv** [comment]
what configuration do you have? Is this something that can be reproduced in a sample repository? It seems a certain response isn't json, but I don't know where without the stacktrace and reproducible example

**Comment by nazanin-bayati** [comment]
Here is the project repository
https://github.com/nazanin-bayati/gatsby-blog-algolia

**Comment by Haroenv** [comment]
I've your repository with my credentials and I don't see this error unfortunately. Do you have a stack trace of the error happening?

**Comment by nazanin-bayati** [comment]
Did take a Build? I face the error in Gatsby build

**Comment by Haroenv** [comment]
Yes, I did `npm run build` and saw all the information in my dashboard. Can you give the full crash information?

**Comment by nazanin-bayati** [comment]
![Screenshot from 2021-05-04 19-52-30](https://user-images.githubusercontent.com/75728944/117027949-72aeb180-ad12-11eb-9d3e-be9d792ed543.png)

**Comment by Haroenv** [comment]
Are you using a vpn or something similar that could cause the response to be changed? Can you scroll lower in the output to show the whole stack trace (preferably as text)

**Comment by nazanin-bayati** [comment]
You were right, it was the vpn problem thanks for your help

**Comment by Taylorsuk** [comment]
@nazanin-bayati do you have anymore information on what was happening with the VPN. I have got this issue now and it's very difficult to pin down, however it seems to be our enterprise customers who are flagging it. Sometimes it work, others they are getting this error. I did wonder if there was some sort of rate limiting on their VPN, and if we ping off too many searches as the user types for example, then the network request was being flagged. 

Any info / help you have would be great.
