### ISSUE TITLE
The plugin deletes entries in some specific cases.

### ISSUE THREAD

**Issue by DanielRiveraHQ** [algolia/gatsby-plugin-algolia#136]
I'm having a peculiar issue; you might know the answer. I'm using gatsby sourcing WordPress and adding data from there to Algolia. To add, I'm using Gatsby Cloud. 

If I push an update to my repo or generate a build manually, all works well, and the number of records shows correctly in Agolia. Still, as soon someone updates data in WordPress, it triggers a quick update, and after finished, the records of an index reduce to 50. Sometimes the records reduce to zero.

If I trigger a manual deploy or update something in the code that triggers a deploy, the index records get back to the real number.

Here is how it looks after deploying from an update in the code:
https://share.getcloudapp.com/Jru4dbyg

I trigger a build changing something in WordPress:
https://share.getcloudapp.com/8LubRj82

And it reduces the records to 51:
https://share.getcloudapp.com/4gu2kjAz

The number of records from WordPress:
https://share.getcloudapp.com/5zuB4Xpv

**Comment by Haroenv** [comment]
> it triggers a quick update

Could you explain how this triggers, and what it triggers?

Thanks!
