### ISSUE TITLE
Parameter to disable empty queries

### ISSUE THREAD

**Issue by Vacilando** [algolia/gatsby-plugin-algolia#138]
Our search index has been completely used up by thousands and thousands empty queries of some bored person or bot, with the Algolia account blocked as a result.

At https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/js/ we see it should be possible to disallow empty queries.

How to disable empty queries using gatsby-plugin-algolia? 
Could there be a parameter that users could employ to indicate theat empty queries should be blocked?

**Comment by Haroenv** [comment]
> How to disable empty queries using gatsby-plugin-algolia?

Gatsby-plugin-algolia doesn't prescribe a frontend, assuming you're using React InstantSearch, the guide is here: https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/react/

Hope that helps!

**Comment by Haroenv** [comment]
As this is unrelated to the plugin, I'll close the issue. Have a great day!
