### ISSUE TITLE
Limit searches to 3 characters or more

### ISSUE THREAD

**Issue by yasirhaleem** [algolia/gatsby-plugin-algolia#139]
can we limit search to start after 3 or more characters ? so it hit algolia only if there is more than 3,4 characters in search box

**Comment by yasirhaleem** [comment]
i tried settting condition  on setQuery but it didn't worked as expected

`<InstantSearch
          searchClient={searchClient}
          indexName={indices[0].name}
          onSearchStateChange={({ query }) =>
            query.length > 4 ? setQuery(query) : null
          }
        >`

**Comment by Haroenv** [comment]
You can make a custom searchbox using connectSearchBox and only call `refine` once the query is longer than 3 characters.

Since this is unrelated to Gatsby, I'll close this issue, but if you're stuck further, please make a sandbox with what you have and I'll have a look

**Comment by yasirhaleem** [comment]
@Haroenv Thank you so much for the reply.

i'm using `gatsby-plugin-aloglia` i tried the following it doesn't show until i enter 5th character but it always hit the algolia even if i enter 1st character 

`<InstantSearch
          searchClient={searchClient}
          indexName={indices[0].name}
          onSearchStateChange={({ query }) =>
            query.length > 4 ? setQuery(query) : null
          }
        >`

can we pass it as paramater to plugin ?

**Comment by Haroenv** [comment]
As said, this has nothing to do with Gatsby, and isn't an option for the default searchbox. What you'll need to do is:

1. make a custom search box: https://www.algolia.com/doc/api-reference/widgets/search-box/react/#connector
2. keep track of the query in local state in the component
3. call refine whenever your trigger has exceeded

Hope that helps!
