### ISSUE TITLE
indices of algolia has no data

### ISSUE THREAD

**Issue by Chad97** [algolia/gatsby-plugin-algolia#140]
After I execute build, algolia doesn't show effective

```
ALGOLIA_APP_ID=xxx
ALGOLIA_API_KEY=xxx
ALGOLIA_INDEX_NAME=xxx
``` 
👆🏻 The above configuration is correct

build tips ` success index to Algolia - 0.002s - options.skipIndexing is true; skipping indexing `

- I don't understand what it means

**Comment by Haroenv** [comment]
You have passed skipIndexing to the configuration, meaning that no objects will be sent to Algolia
