### ISSUE TITLE
Algolia works locally but not in Gatsby Cloud

### ISSUE THREAD

**Issue by theRealHal9000** [algolia/gatsby-plugin-algolia#142]
Hi there,

I've got Algolia search working on my site when I run gatsby develop and I have no errors with the indexing while running gatsby build. I've also set up the environment variables in my Gatsby Cloud account and they match my local .env file exactly. When Gatsby Cloud builds the site I don't get any error messages, but I see this in the Console on the search page:

x-algolia-application-id=undefined

My gatsby-config.js file has these settings:
```
{
      resolve: `gatsby-plugin-algolia`,
      options: {
        appId: process.env.ALGOLIA_APP_ID,
        apiKey: process.env.ALGOLIA_ADMIN_KEY,
        queries: require("./src/utils/algolia-queries"),
      },
    },
```

Am I missing anything? Or is there something else I should try?

**Comment by Haroenv** [comment]
Unfortunately that's not really much information to go off, but I guess that the environment variable isn't actually set in exactly the same way, seeing as the app id is logged as undefined

**Comment by theRealHal9000** [comment]
Hey, thanks for replying. I realized that I had a typo in the environment variable name inside a component. I forgot that the only location wasn't gatsby-config.js. Then everything worked.

**Comment by Haroenv** [comment]
glad that it worked!
