### ISSUE TITLE
How to define searchable attributes and tags?

### ISSUE THREAD

**Issue by lucashfreitas** [algolia/gatsby-plugin-algolia#144]
Hello,

Does this plugin allow us to define searchable attributes, facet filter and tags when creating the index?  All of this can be achieved using the Javascript Object returned into `query`, `tranformers`? 

Thanks

**Comment by lucashfreitas** [comment]
I have managed to do that in algolia console so I will close this for now. Thanks :)

**Comment by Haroenv** [comment]
It can indeed be done via the dashboard, or alternatively via the "settings" key in the plugin: https://github.com/algolia/gatsby-plugin-algolia#settings
