### ISSUE TITLE
Does the plugin work with 8base queries?

### ISSUE THREAD

**Issue by anyav77** [algolia/gatsby-plugin-algolia#145]
My Gatsby site retrieves the data from 8base.  Is it possible to query this external data with this plugin?  or is it better to push the data directly into Algolia via API?

**Comment by Haroenv** [comment]
No idea what 8base is, but the flow is as following:

If the website is the source of truth, and you want to search everything available on the website, from multiple sources, use this plugin (make sure the algolia plugin is the last one you use). 

This means however you link the update of your search index and the website, that could be more or less frequent than the actual info updates

If you only have one source of content, and it doesn't have the same update frequency as the website, it can be interesting to integrate directly with it via the api clients.

**Comment by anyav77** [comment]
Hi Haroenv, thank you for the quick response!  

Just to clarify:
I have two websites: Magento and Gatsby.  The goal is to display the search results for both of them on my Gatsby site.  So, I will be using multiple indexes.
The Gatsby site connects to the backend platform, 8base (a database management service).  This is where the data is coming from.  I would like to search some database tables and display the filtered results.

I don't know how frequently the website will be updated, but I hope the frequency will increase over time.  Given this background, is it better to use 8base to Algolia API and to pull the data directly from Algolia?

**Comment by Haroenv** [comment]
if the only data shown on your Gatsby site is either already in Algolia or coming directly from 8base (no transformations or something happening on the Gatsby side), you'll probably have an easier time using an API client and updating directly based on 8base.

Of course it's still possible to use this plugin too, but there's not a lot of difference.

I'll close this issue now, but if you have more questions, feel free to ask
