### ISSUE TITLE
Make "only works on build" more visible somewhere in the readme

### ISSUE THREAD

**Issue by cesarvarela** [algolia/gatsby-plugin-algolia#149]
I see that is mentioned, but the text gets lost in the readme.

It would help devs not waste time trying to understand why it doesn't upload the index, like https://github.com/algolia/gatsby-plugin-algolia/issues/148 and me.

**Comment by Haroenv** [comment]
🤔 I agree, although

> You can specify a list of queries to run and how to transform them into an array of objects to index. When you run `gatsby build`, it will publish those to Algolia.

is already the first line of the readme, what would you change for it to make sense?

**Comment by cesarvarela** [comment]
Not really a strong preference, maybe a third item here: 
![image](https://user-images.githubusercontent.com/1172479/131461086-beefbef7-c785-4012-a70a-7072e648514f.png)

When I skimmed through the readme I only read those 2 items :D

Maybe with a warning emoji

> ⚠️Only updates the index when you run `gatsby build`

**Comment by Haroenv** [comment]
I added a diagram, but wondering if maybe a log on dev also makes sense? it could be noisy of course, there's plenty plugins that work on build.

**Comment by cesarvarela** [comment]
Oh yeah it does, I've looked for some algolia-related log on dev and because I didn't find any I thought I had the wrong config.
