### ISSUE TITLE
Builds error when using replicas

### ISSUE THREAD

**Issue by Ash-Matter** [algolia/gatsby-plugin-algolia#157]
Hi, 
I have 4 replicas attached to an index that is being updated by this plugin and everytime I build, I get the following error:

`Error: A replica index is already replica of another index`

![image](https://user-images.githubusercontent.com/56417282/143792346-73177dba-a46e-4521-af9d-80ba781668dc.png)

I can temporarily remove the replicas from the primary index and the build will go though, but this is not ideal.
I added a copy of the repo to the `plugins` folder so I could debug this and found that the error occurs during the `setSettings` process (https://github.com/algolia/gatsby-plugin-algolia/blob/master/gatsby-node.js#L335-L339)

If I'm putting 2 and 2 together correctly here, it would seem that this is trying to update the existing replica with the new tmp index and erroring because its already attached to the original index.

Commenting the `forwardToReplicas` variable out has no effect on this either so I'm at a bit of a loss now given the `setSettings` function is from `algoliasearch` package.

**Comment by Haroenv** [comment]
hmm, the correct behaviour should be implied by https://github.com/algolia/gatsby-plugin-algolia/blob/e7c80b153ff33535f144effa5b80337052ad0bdb/gatsby-node.js#L410-L445, essentially avoiding setting the `replicas` setting, unless it's to the main index. Do you have `replicaUpdateMode` set in your settings? Do you have `enablePartialUpdates`? Thanks!

**Comment by Ash-Matter** [comment]
@Haroenv Heres the current setup:
![image](https://user-images.githubusercontent.com/56417282/143851135-e66c086c-8909-4910-8dc2-df69d61d391d.png)
Open to suggestions on how to get around this.

**Comment by Haroenv** [comment]
Hmm, seems like a big then, if you don't pass any settings, then there should be nothing related to replicas either. If you enable partial updates, does the behaviour still exist?

**Comment by Ash-Matter** [comment]
@Haroenv thats amazing - enabling the partial updates did the trick (also cleared out about 100 records too).
Would be a good one to throw into the documentation for future note.

Cheers for the soundboard!
