### ISSUE TITLE
Question re: Algolia Search

### ISSUE THREAD

**Issue by Isaac-Tait** [algolia/gatsby-plugin-algolia#163]
I have Algolia setup to search my blog posts `content -> blog` but I have about 30 "static" pages `src -> pages` that I would like to add to a separate Algolia indices. My first issue is that I have only found one article discussing this specific search scenario and the author's example was broken.

Problem 1: All the Gatsby documentation I have found is on setting up a search of the blog only, which I already have up and running...

Problem 2: I have been playing around with GraphQL queries to populate the separate "static pages" indices much like it is done with the blog post indices. However, I cannot get a query to load the content of the "static pages" - it just returns "null".

Has anyone implemented multiple indices Algolia search before (more specifically I am only looking to index my "static" pages **not** the blog pages/posts)?

**Comment by Haroenv** [comment]
If you set up multiple queries, you can specify an indexName for each of them, and then you can use multi-index search to retrieve those. Could you clarify where you're stuck? Are the items indexed in the two indices? 

If you have a reproducible example, that would be useful

**Comment by Isaac-Tait** [comment]
> If you set up multiple queries, you can specify an indexName for each of them, and then you can use multi-index search to retrieve those.

That is what I am interested in setting up. For my blog posts I created a `graphql` query that populates the Algolia index. Something like this is what I have: 

```
const pageQuery = `{
  pages: allMarkdownRemark(
    filter: {
      fileAbsolutePath: { regex: "/${escapeStringRegexp(pagePath)}/" },
    }
  ) {
    edges {
      node {
        id
        frontmatter {
          title
        }
        fields {
          slug
        }
        excerpt(pruneLength: 5000)
      }
    }
  }
}`
```

I then wanted to populate a separate Algolia index with another `graphql` query for my "static" pages (e.g. about, history, staff, programs, etc...). These pages change from time to time (new staff members, new programs, discontinued programs, etc...) and so I would need the Algolia index to repopulate itself (much like the blog posts index updates when I add a blog post or update it) when there is a change.

I spent quite a bit of time digging through `GraphiQL` to try and create a query that could push my static pages into an Algolia index with no success. However, my queries were returning `null`. 

I am thinking that perhaps I need to use `createPage` within `gatsby-node.js` so that my static pages will have queryable parameters that I can "access" using a graphql query that will then send them to my separate Algolia index... This is where I am getting stuck. [Here](https://s.tape.sh/q7pIvXbj) is a video illustrating the problem I am running into

**Comment by Haroenv** [comment]
Have you checked `allSitePages`? I feel like that's what you're looking for, for those static pages. This is however more of a Gatsby than a Gatsby plugin algolia question, so feel free to ask your question on their support pages :)

**Comment by Haroenv** [comment]
Sorry, as you already found out, this plugin fits your use case as far as I can tell, I'm just not sure which query you're looking for, as I'm not that deep of an expert in Gatsby's query format, sorry!

**Comment by Isaac-Tait** [comment]
Thank you for your help, I do appreciate it. I will keep working at this and report back when I get it sorted. Cheers! 😄
