### ISSUE TITLE
Support for Gatsby 5

### ISSUE THREAD

**Issue by Vacilando** [algolia/gatsby-plugin-algolia#166]
warn Plugin gatsby-plugin-algolia is not compatible with your gatsby version 5.2.0 - It requires gatsby@^2.0.0 || ^3.0.0 || ^4.0.0

**Comment by Haroenv** [comment]
Have you tried the plugin with Gatsby 5 ignoring the warning, is there anything that doesn't work?

**Comment by Haroenv** [comment]
I've released this in v1, thanks for indicating
