### ISSUE TITLE
Plugin breaking in Gatsby 5

### ISSUE THREAD

**Issue by yl92** [algolia/gatsby-plugin-algolia#169]
Trying to upgrade our project to Gatsby 5 but encountered this error while making production builds:

```
failed to index to Algolia Cannot read properties of undefined (reading 'contentDigest')
```

Likely as a result of Gatsby 5's [upgrading to GraphQL 16](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#update-to-graphql-16).

**Comment by Haroenv** [comment]
Have you used the latest version of the plugin, 1.0.2? If you have your configuration you can share, that would be good too!

**Comment by yl92** [comment]
Thanks, just upgraded to `1.0.2` – didn't know that `internal.contentDigest` is required before this (it seemed like it was working fine without it). Thanks for sorting this!

**Comment by Haroenv** [comment]
No worries, that's a simplification and the breaking change of v1 to allow far less network requests and complexity needed in the plugin :)

**Comment by chhourbro** [comment]
`1.0.2` works when you build locally but seems to be throwing the same error with Gatsby cloud builds.

**Comment by Haroenv** [comment]
You probably don't have the contentDigest in Gatsby cloud then. If you have a reproduction, please open a new issue :) @chhourbro
