### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by samaritanau** [algolia/gatsby-plugin-algolia#170]
Hi, 

Thanks for the plugin, it's awesome. We have several sites using it that have now got enough content (or nodes?) that we run out of Javascript memory when we get to the postbuild indexing. Is there any way to batch the indexing or allow us to work around this issue?

Regards,
Henry

**Comment by Haroenv** [comment]
Hey @samaritanau, that's indeed something of an assumption I made to simplify this plugin, that everything would fit in memory.

Do you know at which point the process runs out of memory? Is it when fetching the existing hits, or when running the Gatsby query for the next hits?

**Comment by samaritanau** [comment]
Hey @Haroenv , thanks for responding, in this case it's when running the Gatsby query and creating the objects to be indexed. I'm looking at creating an index per locale at this point, kick the can down the road :)

**Comment by Haroenv** [comment]
Yes, if it's sharded per index, I can make sure that not everything is loaded in memory at once (although once you've done that change, and it didn't work, I can look more in what exactly gets loaded at which point)

**Comment by samaritanau** [comment]
Separating out to indexes per locales (we have 11) seems to have solved the memory issue for us at the moment. We do however have to run the queries non-concurrently to make it work it seems, otherwise Algolia stops responding to our requests and we get the  "Unreachable hosts - your application id may be incorrect" error. Thanks for your help.

**Comment by Haroenv** [comment]
That sounds good. For now I'd recommend staying at this solution. If you have any idea on how to prevent all indexing to be concurrent (or at which level it seems to wait too long), I'm happy to accept a pr!
