### ISSUE TITLE
Add indexName to the gatsby cache key

### ISSUE THREAD

**Issue by yathomasi** [algolia/gatsby-plugin-algolia#171]
I think it would be better to set the gatsby cache with the indexName. eg: `` `algolia-objects-${indexName}` ``
https://github.com/algolia/gatsby-plugin-algolia/blob/d6a8eddd49e894ac892eab9698a2dec90a3c73d4/gatsby-node.js#L233

**Comment by Haroenv** [comment]
Oh, that's a great catch, thanks! Not many people must be using multiple indices, or they would have found this bug already.

**Comment by MartijnHols** [comment]
Hah! I just started doing that today. It was driving me crazy why 4 out of 212 records were missing until I started diving into the code for this library. Thanks for the fix.
