### ISSUE TITLE
Why partial partial update is no more optional ?

### ISSUE THREAD

**Issue by yathomasi** [algolia/gatsby-plugin-algolia#172]
Is there a way to force-rerun the indexing? 

I have a use case that has changed the `id` so now if I index it will simply add it to the existing index causing duplicates. I think it's already an issue as it should remove the existing ones. 

Or, it would be better to allow an option to fully reindex?

**Comment by Haroenv** [comment]
I didn't yet think of that feature, not too sure how it would fit in configuration, but you can in this process reindex manually:

- change configuration (can be local) to index on a different indexName
- index in the new index
- moveIndex from the new index to the existing index
- change configuration back to original index

Now the data should be completely in sync again.

Should there be a function, option to reindex? it would make sense for local building, but I don't really see the point of it for published deploys.

**Comment by yathomasi** [comment]
Let me try to put this from a different perspective. 

Basically, we have this use case(edge case) scenario, where the `objectID` or `id` got changed. Now, when it tries to reindex or compares with the existing index, sees the array of data as new data with different `id` causing duplicates of data in the index.

So, what I think here is we don't have the function to delete the data from the index as it no more exists.  I guess that's an issue.

**Comment by Haroenv** [comment]
Interesting, normally the outdated object should have been removed:

https://github.com/algolia/gatsby-plugin-algolia/blob/452bad59dfbe0664dca85b486429c17e556b4442/gatsby-node.js#L338

Did the indexing not complete correctly? 

If it's a one-off, you can also manually delete those objects from the index I believe

**Comment by yathomasi** [comment]
That's the surprise for me too as I also saw the code regarding that. For now I have fixed my issues by simply using new index but I will try to give another look when I run into this again.

**Comment by Haroenv** [comment]
Thanks. If this happens again I'd rather know what actually caused the incorrect index than build in some mechanism to reindex, as the location that should be ran isn't clear.

**Comment by Haroenv** [comment]
As I haven't seen any other occurrences of this, I'm going to guess the indexing didn't complete successfully in that one case. As it's hasn't yet been able to be reproduced, I'll close the issue for now
