### ISSUE TITLE
Enrich your records with Google Analytics data

### ISSUE THREAD

**Issue by t2ca** [algolia/gatsby-plugin-algolia#174]
Hello!

I have followed this [guide](https://www.algolia.com/doc/guides/managing-results/must-do/custom-ranking/how-to/enrich-your-records-with-google-analytics-data/) to enrich our algolia records.

The issue we are having is that our subsequent gatsby builds are removing the "pageviews" attribute that the script had created.

Looking for advice on how we can persist the google analytics data in our records.

Thank you!

**Comment by Haroenv** [comment]
You indeed can only have one source of truth for your records, and this plugin assumes it's the only thing writing to the Algolia objects. 

I can see two solutions:

1. fetch the google analytics data before pushing in the Gatsby data. This can be done in the `transformer` function, or possibly even in the graphql query if there's a way to access the google analytics data through a Gatsby plugin.
2. fork this plugin to use `partialUpdateObject`, knowing that it would not remove an attribute that was previously present on an object.

Depending on where you're running the google analytics script, and how permanent it is, you could choose either of these options.
