### ISSUE TITLE
Extracting chunks of long text as its own record 

### ISSUE THREAD

**Issue by ch264** [algolia/gatsby-plugin-algolia#177]
I would like to break up long text pages into individual records. 

I can do that in my query like so: 

```
const queries = [
  {
    query: pageQuery,
    transformer: ({ data }) => {
       return data.allMarkdownRemark.edges.map(edge => edge.node).reduce((acc, post) => {
          const pChunks = post.rawMarkdownBody.split('##');
          
          const chunks = pChunks.map(chnk => ({
            objectID: post.id,
            headings: post.headings,
            fields: post.fields.slug,
            title: post.frontmatter.title,
            internal: post.internal,
            content: chnk
          }));
          return [...acc, ...chunks]
        }, [])
    },
    indexName: algoliaIndex,
  },
];
```

In the console I can see that the breaking up into individual objects works and follows [Algolia's recommendation](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/) on splitting up long documents

![Screenshot 2023-05-16 at 3 37 15 PM](https://github.com/algolia/gatsby-plugin-algolia/assets/36343528/2ec20c10-e3ba-4943-bbc9-4ec55d3625c2)

However, when I run 'gatsby build' only the last paragraph of each page makes it into the Algolia index. 

<img width="1176" alt="Screenshot 2023-05-25 at 10 35 38 AM" src="https://github.com/algolia/gatsby-plugin-algolia/assets/36343528/dd01ae33-7d3a-4584-9601-cc05a65e14c2">

Is there a way to ensure that all split up objects from a page get into the Algolia index? I am unsure on how to troubleshoot. Is breaking up long text documents possible with this plugin? 

Thanks so much for your help

**Comment by Haroenv** [comment]
Hi, that's because you use the same objectID for every part of the chunk, you need to include the chunk index in there as well. The fixed version would be:

```js
const queries = [
  {
    query: pageQuery,
    transformer: ({ data }) => {
       return data.allMarkdownRemark.edges.map(edge => edge.node).reduce((acc, post) => {
          const pChunks = post.rawMarkdownBody.split('##');
          
          const chunks = pChunks.map((chnk, index) => ({
            objectID: post.id + '-' + index,
            headings: post.headings,
            fields: post.fields.slug,
            title: post.frontmatter.title,
            internal: post.internal,
            content: chnk
          }));
          return [...acc, ...chunks]
        }, [])
    },
    indexName: algoliaIndex,
  },
];
```

**Comment by ch264** [comment]
Thanks a million for your help @Haroenv. That worked!
