### ISSUE TITLE
Gatsby internal.contentDigest is a poor source for deciding whether content needs to be updated

### ISSUE THREAD

**Issue by Swissbite** [algolia/gatsby-plugin-algolia#182]
I may be wrong, but as far as I understand Algolia you have to have one object per page (and one index per language) to use it properly.

In versions prior to release 1.x, there was the ability to specify on which fields the update hash should be calculated. This was wonderful for headless CMS with composable content architecture. As a developer, I just had to make sure that my calculated hash took all child elements into account. This would reduce the possibility of conflict with any existing fields in my graph nor would it change any behaviour.

With the change and relying solely on the field `internal.contentDigest` suggests an automatism, which has two basic problems:

1. it relies on a field from GatsbyJS which is explicitly declared as **internal**.
2. this field does not take into account other nodes in the graph which could be connected to the content.

In the following chart is a simple example of how linked content works in headless systems like Contentful, DatoCMS, strapi.io etc. when in use with gatsbyJS as frontend framework.

And the main issue is: If I would update any FAQ entry because there was a typo, there will be no change in the internal objects of any of the pages.

```mermaid
flowchart TD
classDef leftTextFlow text-align:left;
    P1["`**Page1**
internal: { contentDigist: lastUpdatedDateTime},
slug: /page_1
title: Page 1 with references
references: [FAQ_1, FAQ_2]
`"]:::leftTextFlow
    P2["`**Page2**
internal: { contentDigist: lastUpdatedDateTime},
slug: /page_2
title: Page 2 with references
references: [FAQ_1, FAQ_3]
`"]:::leftTextFlow
FAQ_1["`**FAQ 1**
internal: { contentDigist: lastUpdatedDateTime},
question: Why 1?
answer: Because 1
`"]:::leftTextFlow
FAQ_2["`**FAQ 2**
internal: { contentDigist: lastUpdatedDateTime},
question: Why 2?
answer: Because 2
`"]:::leftTextFlow
FAQ_3["`**FAQ 3**
internal: { contentDigist: lastUpdatedDateTime},
question: Why 3?
answer: Because 3
`"]:::leftTextFlow
P1 --> |references| FAQ_2
P2 --> |references| FAQ_3
P1 & P2 --> |references| FAQ_1
```

## Possible workarround:
- Do not query the internal object with gatsby but use the transfrom function to calculate your own hash, and fake it like it would by the field on `internal: { contentDigest: string }`

## Suggested way to fix this behaviour by still have this internal reference as default:
- Re-enable the option of `matchFields`
  - If used, it overwrites the default behaviour

**Comment by Haroenv** [comment]
Yes, that's an interesting point, there was an issue yesterday as well (#181, cc @drooJohnson) that was linked to contentDigest not working as needed. 

I see two options here:


1. create a simple hash of the content of the _record_ before indexing (takes some computing power, but likely isn't too bad)
2. allow override of the "digestField" so people can compute their own hash / combine existing fields (simple, but not sure if this would be too discoverable)

If you have any idea of how it should be most discoverable, I'm open to ideas.

**Comment by Swissbite** [comment]
Two things to mention:

1. Algolia updates an object 1:1, so there is no "partial Update" of an object.
2. All this calculation is just done to reduce the load and costs for Algolia

In the previous versions you could define the fields which acts as a hash.
Because of this, we calculated a hash post-query in the transformer function, and named that field `hash`.
And because our paths where not part of the content itself (the field `slug` is not a full qualified path on a server), we where able also to set that as a configuration.

Our configuration looked like:
```js
{
      appId: GATSBY_ALGOLIA_APP_ID,
      apiKey: ALGOLIA_WRITE_API_KEY,
      indexName: `${GATSBY_ALGOLIA_INDEX_NAME_PREFIX}`
      queries: algoliaQueries(languageTag),
      enablePartialUpdates: true, // default: false <<-- This got removed due to the change of requiring the internal.contentDigest field.
      matchFields: ['path', 'hash'], // default: ['modified'] <<-- There was the interesting magic
      skipIndexing: skipAlgoliaIndexing, // default: false <<-- This got removed, which is another issue but simple to solve
    }
````

And our transformer for a single object in the data array response was like:
```js
function transformer(item) {
 const result = {
      ...item,
      objectID: `${item.contentful_id}_${item.node_locale}`,
      hash: createHashFromInputData(item),
      path: createPathFor(item),
    };
}
````
If you are
- aiming for a "one-size-fits-all" solution, you need to create a method that calculates hashes for each object tree or traverse all objects to calculate a hash over all contentDigest
- aiming for a simple solution but open for any kind of data structure, re-enable the matchFields option and explain in your docs what is happening and why.

IMHO a "one-size-fits-all" solution will never be good enough. So let the creators / developers be responsible on how to calculate the hash.

**Comment by Archunan-MDLZ** [comment]
Hi @Swissbite  Any update on this, same issue we are also facing with contentDigest. The post helped to narrow down the issue. Here is another thought, function transformer(item) { contentDigest we can add current time/timestamp/random hash, instead of adding new field. just a thought till your PR updated to plugin

**Comment by Haroenv** [comment]
You're right, the best way to ensure you're in charge is by consistently using the internal.contentDigest field (which also means the code doesn't need to be updated to deal with an array of fields instead of only one.

**Comment by Haroenv** [comment]
I added this to the FAQ and documentation, so I think this issue is handled for now.
