### ISSUE TITLE
Partially update not updating existing object in index

### ISSUE THREAD

**Issue by Archunan-MDLZ** [algolia/gatsby-plugin-algolia#184]
Hi Team @Haroenv 

We are facing issue with update existing object in index, Here is our use case 
Initally we feed the data to index and later,
Plugin used : https://www.gatsbyjs.com/plugins/gatsby-plugin-algolia/
our gatsby configuration for algolia 

```
        enablePartialUpdates: true, // default: false
        matchFields: ['publishDateTimestamp', 'content.date'], 
        concurrentQueries: true, // default: true
        skipIndexing: false, // default: false, useful for e.g. preview deploys or local development
        continueOnFailure: true, // default: false, don't fail the build if algolia indexing fails
```

In every graphql contentDigest added

```
        internal {
          type
          contentDigest
          owner
        }
```

when there is change in these two fields not getting updated until we clear the index data and give gatsby build
what we have to to achieve to update existing object/record. is there any cache to removed to get new value every time. 
As per documentation  enablePartialUpdates :false will recreate index data every time build runs. But not happening like that.
I have referred issue page: https://github.com/algolia/gatsby-plugin-algolia/issues
Can anyone explain why not updating and help with possible options

**Comment by Haroenv** [comment]
I can see this is configuration for the non-latest version, as partial updates and match fields are no longer valid options now. Do you have a reproduction where I can see the issue?

**Comment by Archunan-MDLZ** [comment]
Hi @Haroenv 

Thanks for the quick feedback.
Please see this timestamp is articledate field got updated on the source system(contentful pages)
<img width="454" alt="image" src="https://github.com/algolia/gatsby-plugin-algolia/assets/118916934/2d040bb9-835b-4c0c-934c-4c4fc6843544">
Still its not updated. is there way we can connect and show you screen and data

**Comment by Haroenv** [comment]
For technical support, you can reach [support](https://support.algolia.com/hc/en-us), if you have a reproducible example of what you think can be a bug, you can use issues here.

Are you actually using the latest version of the plugin?

**Comment by Archunan-MDLZ** [comment]
Hi @Haroenv ,

Yes i updated to latest version of gatsby plugin 
<img width="320" alt="image" src="https://github.com/algolia/gatsby-plugin-algolia/assets/118916934/905eb1bd-8d37-42ce-90c8-e9304323e8e2">
I see that algolia don’t provide support for the community plugin.

I will check with algolia support

**Comment by Haroenv** [comment]
I'd recommend you create an easy to use reproduction, then we can see whether there's anything misbehaving in the plugin. For now I'll close this issue and you can open a new one with repro
