### ISSUE TITLE
Attributes for faceting being removed?

### ISSUE THREAD

**Issue by moreguppy** [algolia/gatsby-plugin-algolia#22]
- From the dashboard I assign some attributes which will be used for refinement over on Display > Faceting
- When the site gets rebuilt (on content change or whatever) the faceting options are reset

Is this because I am not setting these in `gatsby-config.js`? If so how do I do that?

Thanks!

**Comment by Haroenv** [comment]
Exactly, this plugin assumes ownership over all settings, and will always set those from the file, and overwrite what's on the dashboard. You can fix this indeed by setting it in the file. 

the key is called `settings`, and is done for each of the queries

Looks like I forgot to add it in the readme, so I just added that, thanks!
