### ISSUE TITLE
The page on the Gatsby blog is showing an incorrect .env file 

### ISSUE THREAD

**Issue by bramses** [algolia/gatsby-plugin-algolia#28]
<img width="672" alt="screen shot 2019-02-22 at 10 52 19 am" src="https://user-images.githubusercontent.com/3282661/53253801-1068b980-3690-11e9-8d2b-fbaf2427a3be.png">

this doesn't show that users need to have an API key, and some readers may get confused. The README is correct though

**Comment by Haroenv** [comment]
Where did you see that @bramses ?

**Comment by bramses** [comment]
@Haroenv https://www.gatsbyjs.org/packages/gatsby-plugin-algolia/?=algol

**Comment by Haroenv** [comment]
This has been fixed since the last release but no new release has been done since yet: https://github.com/algolia/gatsby-plugin-algolia/commit/8bc3959f6d23fc683fa9b7041391faaa8d831f5d
