### ISSUE TITLE
Error: Unable to find plugin "gatsby-plugin-algolia". Perhaps you need to install its package?

### ISSUE THREAD

**Issue by hendra-go** [algolia/gatsby-plugin-algolia#32]
I Use windows 10.

After updating to 0.3.1 this bug happens. I fix this only by adding empty index.js
Somehow when publish to npm, the index.js file is not included.
I guess the index.js file is important for the gatsby-plugin-algolia to be found by gatsby.

**Comment by Haroenv** [comment]
oh, good call, I didn't realise, fixing it now.

**Comment by Haroenv** [comment]
0.3.2 should have fixed this :)
