### ISSUE TITLE
Manually trigger index

### ISSUE THREAD

**Issue by samdenty** [algolia/gatsby-plugin-algolia#33]
Is there a way of manually triggering the index operation during develop, without performing the whole build-step?

**Comment by samdenty** [comment]
Ah didn't see https://github.com/gatsbyjs/gatsby/issues/2698#issuecomment-488041539 in prev issue

**Comment by Haroenv** [comment]
I did not do this on purpose, because people usually won't want their data indexed during develop because they have to pay for it
