### ISSUE TITLE
Facets and Settings Irregularly Missing

### ISSUE THREAD

**Issue by johndaskovsky** [algolia/gatsby-plugin-algolia#37]
There is an irregular bug with the plugin which is causing the facets and other settings which are set up in the plugin config to be sporadically missing from the updated index.

I noticed that when this problem occurs, the settings and facets exist on the `tmp` version of the index but not on the primary version.

This issue has happened several times during our build over the last 3 months and is difficult to replicate. In testing locally today, 2 of the 3 times resulted in one of our indexes missing its settings, and the third time the settings were present. 

The irregularity of the bug makes me suspect a race condition at play but I've not been able to identify the problem.

**Comment by Haroenv** [comment]
thanks!

**Comment by Haroenv** [comment]
published in 0.3.4
