### ISSUE TITLE
Add an example Gatsby app to verify PRs

### ISSUE THREAD

**Issue by Haroenv** [algolia/gatsby-plugin-algolia#4]
Tests might be quite hard here, but an example should be good. @phil-linnell, do you have one you can easily PR?

**Comment by phil-linnell** [comment]
I can look into this next week. A full on example dir or just elaboration of README?

**Comment by Haroenv** [comment]
Full example dir (excluded on npm) with a basic example would be great since it’ll allow to test easily

**Comment by Haroenv** [comment]
simple example was added in https://github.com/algolia/gatsby-plugin-algolia/commit/2db1b90f82ee6ef5ca44f74ca4806c6f9c598fc0
