### ISSUE TITLE
Add option to create index it it does not exist

### ISSUE THREAD

**Issue by krvajal** [algolia/gatsby-plugin-algolia#52]
Currently you need to create the index first in the Algolia dashboard for this plugin to work. 
I would be nice if this plugin could create the index for me it the specified index does not exists yet.

**Comment by Haroenv** [comment]
Ah, that's interesting behaviour, it must have regressed in a recent version, since originally the plugin made the index. If you're feeling adventurous, any operation, like doing an empty "setSettings" creates an index.

**Comment by krvajal** [comment]
I will give it a try, thx
