### ISSUE TITLE
read and uses settings from the original index when settings argument is not given

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/gatsby-plugin-algolia#57]
If user doesn't pass `settings` argument, then we need to read the settings from Algolia server and apply them to the new temporary index. Otherwise, the settings will be lost.

https://github.com/algolia/gatsby-plugin-algolia/blob/master/gatsby-node.js#L167

Before this `if` statement, we could do something like

```js
if (!settings && indexToUse === tempIndex) {
  settings = await index.getSettings()
}
```

If it's the same index, we don't need to get the whole settings and apply them again.

**Comment by Haroenv** [comment]
fix released in 0.9.0
