### ISSUE TITLE
Time frame to exit beta?

### ISSUE THREAD

**Issue by janosh** [algolia/gatsby-plugin-algolia#6]
A Gatsby plugin for Algolia would be awesome and much appreciated! Is there already a timeframe on when to exit beta and add documentation?

**Comment by Haroenv** [comment]
Thanks for your interest, indeed what's missing to move this from beta ➡️ full release is the following: 

1. more expanded documentation
2. proper testing strategy
3. atomic indexing (#5)
4. indexing only changed objects

For now I didn't have the time yet to squash these bugs, but it definitely works, tested in a few different sites so far. 

So a time frame isn't there yet, but I'll make sure to make some time for this when I'm out of holiday and can dedicate some time on this. 

Is there anything else you would like to see @JanoshRiebesell ?

**Comment by janosh** [comment]
@Haroenv Any news yet?

**Comment by Haroenv** [comment]
Atomic indexing has been done, although I'm still going to do a second pass at another time to use less indexing operations. (indexing only the changes). As well as needing proper tests. 

Is there anything you specifically need before using this?

**Comment by janosh** [comment]
@Haroenv I'm struggling to get indexing to work in [this repo](https://github.com/StudentenBildenSchueler/homepage). I'm trying to index all pages sourced from Contentful, but no records are added to the index I created with my Algolia account. Instead, running `gatsby build` I receive the error that `data` is `undefined` in `gatsby-plugin-algolia`'s transformer on line 27 of `gatsby-config.js`.

Could you perhaps take a look at this?

**Comment by Haroenv** [comment]
I'll take a look at that yes :)

**Comment by ErisDS** [comment]
I'm having the exact same issue: Cannot read property 'allSitePage' of undefined, using the exact code from the readme, it errors in the transformer because no data is returned.

The same query works perfectly in the graphql query explorer.

I'm using Gatsby v2 and trying to figure out if there's something that needs migrating?

**Comment by Haroenv** [comment]
@ErisDS would it be possible to create a minimal example? you can start from the one in the repository :)

**Comment by ErisDS** [comment]
@Haroenv I will try, what I can do for now is point you at my branch / commit:

https://github.com/TryGhost/docs/commit/bee70212d0aa3a4cb465a3e085c918c3f9057e11

Hopefully that at least shows that my code is near-identical to the readme. 

The outcome on `gatsby build` is:

![image](https://user-images.githubusercontent.com/101513/46148246-8db60c80-c25f-11e8-9a59-2f54d043f503.png)

**Comment by Haroenv** [comment]
So far I've managed to get your site to build and see that `index to Algolia` seems not to end, but I don't get that error :(

**Comment by Haroenv** [comment]
Weird to be happy to finally have an error, but I'm happy that I now can start debuggin

**Comment by Haroenv** [comment]
I found the issue (and also a source of grey hairs maybe?) https://github.com/TryGhost/docs/pull/7

**Comment by janosh** [comment]
@Haroenv Were you able to reproduce (or even fix) the error in [my repo](https://github.com/StudentenBildenSchueler/homepage)?

**Comment by Haroenv** [comment]
@janosh, I actually saw you made the same kind of “mistake” so I didn’t have to try it out. I’m concinced my pr there was necessary and the fix though :)

**Comment by Haroenv** [comment]
oops, this shouldn't really have closed this issue since it was mixed with the "timeframe out of beta", but I answered that :). As @ErisDS said, I might change the way of passing the query to a more standard way if that makes sense
