### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by caelinsutch** [algolia/gatsby-plugin-algolia#68]
It should be mentioned in the docs that you have to insert this plugin last in the gastby config, otherwise it gives a non-descriptive error and fails. Confused me for quite a while because nowhere mentions this.

**Comment by Haroenv** [comment]
Good point, this is needed to have the right data available to query. Do you want to make a pr to add this?

**Comment by caelinsutch** [comment]
@Haroenv I'll pop it into the ReadME and make a PR

**Comment by caelinsutch** [comment]
#69 has that update

**Comment by Haroenv** [comment]
thanks!
