### ISSUE TITLE
Only take chunksize?

### ISSUE THREAD

**Issue by elvogel** [algolia/gatsby-plugin-algolia#7]
I'm using the Algolia plugin in a static blog site from the [gatsby-starter-hero-blog](https://github.com/greglobinski/gatsby-starter-hero-blog) and I'm running into an issue where my blog post is larger than the document size of 10k. Is it possible to set up the plugin so it merely take the 'first' `chunksize` amount without barfing an error over a larger-sized file? I'd prefer to simply get a warning that it's 'only' taking the first 10k or something, as opposed to trying to whittle down the size of the blog post.

Thanks!

**Comment by elvogel** [comment]
I'd love the split, but in its current state it's barfing on blog posts bigger than 10k

**Comment by Haroenv** [comment]
@elvogel, if I look at https://github.com/greglobinski/gatsby-starter-hero-blog/blob/master/src/utils/algolia.js (in the boilerplate you said you use), it is in fact already chunking the text. Could you give a configuration of a blog which throws that error?

**Comment by elvogel** [comment]
```js
    {
      resolve: `gatsby-plugin-algolia`,
      options: {
        appId: process.env.ALGOLIA_APP_ID ? process.env.ALGOLIA_APP_ID : "",
        apiKey: process.env.ALGOLIA_ADMIN_API_KEY ? process.env.ALGOLIA_ADMIN_API_KEY : "",
        indexName: process.env.ALGOLIA_INDEX_NAME ? process.env.ALGOLIA_INDEX_NAME : "",
        queries,
        chunkSize: 10000 // default: 1000
      }
    },
```

**Comment by Haroenv** [comment]
The chunk size in the options of the plugin is to say how many items to push at once, not how big those items are. That logic should be done by yourself in the query transformer, like how it's done in the hero-blog starter I linked

**Comment by Haroenv** [comment]
Is this still an issue @elvogel? I'm confused about what was going on here, since they _are_ splitting the posts.

**Comment by elvogel** [comment]
I'm in the process of upgrading to the newer version of the site template, which has that code. The version I was using didn't have it. Thanks

**Comment by Haroenv** [comment]
makes sense!
