### ISSUE TITLE
Error on gatsby build but not on gatsby develop

### ISSUE THREAD

**Issue by rootlinux2** [algolia/gatsby-plugin-algolia#70]
When I run gatsby build I'm facing this error!
![image](https://user-images.githubusercontent.com/24574267/81834415-e4dd2380-950e-11ea-9ac9-5ffa745e2206.png)

On gatsby develop

![image](https://user-images.githubusercontent.com/24574267/81835204-f96deb80-950f-11ea-82c6-abdd3d136a6c.png)

**Comment by rootlinux2** [comment]
I don't know why but with VPN gatsby build work, without VPN not, but gatsby develop work with and without.

**Comment by Haroenv** [comment]
The plugin only does something at build, so it's expected that `develop` is unaffected. Does the vpn you use restrict traffic to certain origins alone?
