### ISSUE TITLE
Deleting indexed records

### ISSUE THREAD

**Issue by benknight** [algolia/gatsby-plugin-algolia#71]
How do you use this plugin to tell Algolia to delete a record?

**Comment by Haroenv** [comment]
objects which no longer match in the next indexing, but is still showing in the previous: https://github.com/algolia/gatsby-plugin-algolia/blob/master/gatsby-node.js#L202

Can you clarify what's not working as expected?

**Comment by benknight** [comment]
Closing as resolved.
