### ISSUE TITLE
Working with Prismic's 20 API limit

### ISSUE THREAD

**Issue by andrecalvo** [algolia/gatsby-plugin-algolia#77]
Hey,

I'm using this plugin with the Prismic API. It all works fine but the issue is that Prismic limits the documents returned via their API to 20. 

Is there a way that I can index more than 20 documents at once programatically?

**Comment by Haroenv** [comment]
Why does prismic limit the API like that, do you have docs for this?

**Comment by andrecalvo** [comment]
https://prismic.io/docs/graphql/query-the-api/paginate-your-results

````
The Prismic GraphQL API returns a maximum of 20 documents per request. There is no way to increase this number, so this page explains how you can retrieve more than this initial 20 documents.
````

You can get around this when using the `createPage` function by recursively querying based on the end cursors for example.

I don't think this is possible with this library though?

**Comment by Haroenv** [comment]
Since you’ve created the pages, there should be a way to query for those too, and not directly back to prismic. Maybe you can also explicitly save the downloaded info somewhere?

**Comment by andrecalvo** [comment]
Ah, nice idea :) Thanks

**Comment by Haroenv** [comment]
I assume this is solved now!
