### ISSUE TITLE
Multiple indices

### ISSUE THREAD

**Issue by sedubois** [algolia/gatsby-plugin-algolia#8]
Thanks for this plugin, it's quite helpful. For multi-language sites it's [mentioned](https://www.algolia.com/doc/tutorials/full-text-search/multi-language-search/multilingual-search/) that one index might be needed per language, however the plugin seems to accept a single `indexName`. Could it be enhanced to support that scenario?

**Comment by Haroenv** [comment]
What you can do is instantiate the plugin multiple times, each time with the same configuration, but a separate index. Does that make sense?

**Comment by sedubois** [comment]
OK I see, thanks I will try that.

**Comment by Haroenv** [comment]
Please reopen if the suggested solution doesn't fit the use case you were thinking of!

**Comment by Haroenv** [comment]
I just forgot that you can also specify the indexName per query :)

**Comment by Haroenv** [comment]
Hmm, good call. I don’t know exactly how that would be possible, but I’ll look into it. Instead of reopening this issue, can you open a new one with your snippet about the query variables, and the code you’d expect to work with those variables too? Thanks!

**Comment by brotzky** [comment]
I've run into the same issue. I would love to pass in query variables, but currently it the plugin doesn't allow it. (https://github.com/algolia/gatsby-plugin-algolia/blob/master/gatsby-node.js#L42)

Here's an example of how variables would work
https://github.com/gatsbyjs/gatsby/issues/4050#issuecomment-365887066

I think it would be as simple as adding another key to the index object and passing it through.

Forgive the naming, but the basic goal would be
```
      {
        query,
        queryVariables,
        transformer,
        indexName,
      },
```

```js
const result = await graphql(query, queryVariables);
```

**Comment by Haroenv** [comment]
Would you be willing to make a PR to have the possibility to add query variables @brotzky?

**Comment by brotzky** [comment]
@Haroenv Hopefully soon :)
