### ISSUE TITLE
Synonyms reset after gatsby build

### ISSUE THREAD

**Issue by cameronmcefee** [algolia/gatsby-plugin-algolia#90]
We've noticed that when we configure synonyms via the web UI, upon a gatsby build the list resets. Could this plugin be doing that? I noticed that there's a [`scopedCopyIndex`](https://github.com/algolia/gatsby-plugin-algolia/blob/master/gatsby-node.js#L222) method that seems like it might be intended to preserve synonyms but it doesn't appear to be in use so far as I can tell.

**Comment by Haroenv** [comment]
That seems to be right, as a temporary workaround, you can use the `enablePartialUpdates` option, which doesn't have the issue, since it doesn't copy indices

**Comment by cameronmcefee** [comment]
Ah great, thanks, I'll check that out.

**Comment by Haroenv** [comment]
rules and synonyms are copied int he non-partial version now: https://github.com/algolia/gatsby-plugin-algolia/blob/master/gatsby-node.js#L355 since version 0.21.0
